### ISSUE TITLE
[Bug] cyclic_multi_module_publish test is broken in CI

### ISSUE THREAD

**Issue by lxfind** [diem/move#22]
In #10 we verified that the cyclic_multi_module_publish test would fail even with an empty/dummy change. This indicates that this test is broken. #10 temporarily removed part of the test to make it pass. But we should investigate on why it's broken. Could it be due to the non-determinism of the order of modules being processed?

**Comment by sblackshear** [comment]
@meng-xu-cs, not sure if you have time to take a look at this, but your expertise would be appreciated if so :)

**Comment by meng-xu-cs** [comment]
I'll take a look. Might take me a bit of time to catch up with a lot of exciting code changes but I'll get there. Will report back by Sunday.

**Comment by sblackshear** [comment]
Thank you!!

**Comment by meng-xu-cs** [comment]
Sorry for getting back late. PR #39 is a fix that attempts to restore the original intention of this test. More details can be found in the description of the PR.

**Comment by sblackshear** [comment]
I think https://github.com/diem/move/pull/39 fixed this, please reopen if I got that wrong!
